// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using sahabat_umkm;
using System;

namespace sahabat_umkm.Migrations
{
    [DbContext(typeof(m_news))]
    partial class m_newsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("sahabat_umkm.feature_map", b =>
                {
                    b.Property<int>("feature_map_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("feature_map_id");

                    b.Property<int>("m_feature_id")
                        .HasColumnName("m_feature_id");

                    b.Property<int>("m_user_group_id")
                        .HasColumnName("m_user_group_id");

                    b.HasKey("feature_map_id");

                    b.HasIndex("m_feature_id");

                    b.HasIndex("m_user_group_id");

                    b.ToTable("feature_map");
                });

            modelBuilder.Entity("sahabat_umkm.m_agama", b =>
                {
                    b.Property<int>("m_agama_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("m_agama_id");

                    b.Property<string>("nama_agama")
                        .IsRequired()
                        .HasColumnName("nama_agama")
                        .HasMaxLength(50);

                    b.Property<int>("sequence_agama")
                        .HasColumnName("sequence_agama");

                    b.Property<bool>("status_aktif")
                        .HasColumnName("status_aktif");

                    b.HasKey("m_agama_id");

                    b.ToTable("m_agama");
                });

            modelBuilder.Entity("sahabat_umkm.m_feature", b =>
                {
                    b.Property<int>("m_feature_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("m_feature_id");

                    b.Property<string>("feature_icon")
                        .IsRequired()
                        .HasColumnName("feature_icon")
                        .HasMaxLength(50);

                    b.Property<string>("feature_name")
                        .IsRequired()
                        .HasColumnName("feature_name")
                        .HasMaxLength(100);

                    b.Property<bool>("feature_private")
                        .HasColumnName("feature_private");

                    b.Property<int>("feature_sequence")
                        .HasColumnName("feature_sequence");

                    b.Property<string>("feature_url")
                        .IsRequired()
                        .HasColumnName("feature_url")
                        .HasMaxLength(255);

                    b.Property<int>("m_feature_group_id")
                        .HasColumnName("m_feature_group_id");

                    b.HasKey("m_feature_id");

                    b.HasIndex("m_feature_group_id");

                    b.ToTable("m_feature");
                });

            modelBuilder.Entity("sahabat_umkm.m_feature_group", b =>
                {
                    b.Property<int>("m_feature_group_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("m_feature_group_id");

                    b.Property<string>("feature_group_name")
                        .IsRequired()
                        .HasColumnName("feature_group_name")
                        .HasMaxLength(100);

                    b.HasKey("m_feature_group_id");

                    b.ToTable("m_feature_group");
                });

            modelBuilder.Entity("sahabat_umkm.m_golongan_darah", b =>
                {
                    b.Property<int>("m_golongan_darah_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("m_golongan_darah_id");

                    b.Property<string>("nama_golongan_darah")
                        .IsRequired()
                        .HasColumnName("nama_golongan_darah")
                        .HasMaxLength(5);

                    b.HasKey("m_golongan_darah_id");

                    b.ToTable("m_golongan_darah");
                });

            modelBuilder.Entity("sahabat_umkm.m_jenis_bidang_usaha", b =>
                {
                    b.Property<int>("m_jenis_bidang_usaha_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("m_jenis_bidang_usaha_id");

                    b.Property<string>("nama_jenis_bidang_usaha")
                        .IsRequired()
                        .HasColumnName("nama_jenis_bidang_usaha");

                    b.HasKey("m_jenis_bidang_usaha_id");

                    b.ToTable("m_jenis_bidang_usaha");
                });

            modelBuilder.Entity("sahabat_umkm.m_jenjang_pendidikan", b =>
                {
                    b.Property<int>("m_jenjang_pendidikan_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("m_jenjang_pendidikan_id");

                    b.Property<string>("nama_jenjang_pendidikan")
                        .IsRequired()
                        .HasColumnName("nama_jenjang_pendidikan")
                        .HasMaxLength(100);

                    b.Property<bool>("status_aktif")
                        .HasColumnName("status_aktif");

                    b.HasKey("m_jenjang_pendidikan_id");

                    b.ToTable("m_jenjang_pendidikan");
                });

            modelBuilder.Entity("sahabat_umkm.m_kelurahan_desa", b =>
                {
                    b.Property<int>("m_kelurahan_desa_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("m_kelurahan_desa_id");

                    b.Property<string>("jenis_kabupaten_kota")
                        .IsRequired()
                        .HasColumnName("jenis_kabupaten_kota")
                        .HasMaxLength(20);

                    b.Property<string>("kode_pos")
                        .IsRequired()
                        .HasColumnName("kode_pos")
                        .HasMaxLength(5);

                    b.Property<string>("nama_kabupaten_kota")
                        .IsRequired()
                        .HasColumnName("nama_kabupaten_kota")
                        .HasMaxLength(100);

                    b.Property<string>("nama_kecamatan")
                        .IsRequired()
                        .HasColumnName("nama_kecamatan")
                        .HasMaxLength(100);

                    b.Property<string>("nama_kelurahan_desa")
                        .IsRequired()
                        .HasColumnName("nama_kelurahan_desa")
                        .HasMaxLength(100);

                    b.Property<string>("nama_propinsi")
                        .IsRequired()
                        .HasColumnName("nama_propinsi")
                        .HasMaxLength(100);

                    b.HasKey("m_kelurahan_desa_id");

                    b.ToTable("m_kelurahan_desa");
                });

            modelBuilder.Entity("sahabat_umkm.m_parameter", b =>
                {
                    b.Property<int>("m_parameter_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("m_parameter_id");

                    b.Property<string>("parameter_group")
                        .IsRequired()
                        .HasColumnName("parameter_group");

                    b.Property<string>("parameter_key")
                        .IsRequired()
                        .HasColumnName("parameter_key");

                    b.Property<string>("parameter_value")
                        .IsRequired()
                        .HasColumnName("parameter_value");

                    b.HasKey("m_parameter_id");

                    b.ToTable("m_parameter");
                });

            modelBuilder.Entity("sahabat_umkm.m_pilihan_omzet", b =>
                {
                    b.Property<int>("m_pilihan_omzet_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("m_pilihan_omzet_id");

                    b.Property<string>("pilihan_omzet")
                        .IsRequired()
                        .HasColumnName("pilihan_omzet");

                    b.Property<int>("urutan_pilihan_omzet")
                        .HasColumnName("urutan_pilihan_omzet");

                    b.HasKey("m_pilihan_omzet_id");

                    b.ToTable("m_pilihan_omzet");
                });

            modelBuilder.Entity("sahabat_umkm.m_user", b =>
                {
                    b.Property<int>("m_user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("m_user_id");

                    b.Property<int>("m_user_group_id")
                        .HasColumnName("m_user_group_id");

                    b.Property<bool>("user_active")
                        .HasColumnName("user_active");

                    b.Property<string>("user_email")
                        .HasColumnName("user_email")
                        .HasMaxLength(50);

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnName("user_name")
                        .HasMaxLength(50);

                    b.Property<string>("user_password")
                        .IsRequired()
                        .HasColumnName("user_password")
                        .HasMaxLength(100);

                    b.HasKey("m_user_id");

                    b.HasIndex("m_user_group_id");

                    b.ToTable("m_user");
                });

            modelBuilder.Entity("sahabat_umkm.m_user_group", b =>
                {
                    b.Property<int>("m_user_group_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("m_user_group_id");

                    b.Property<bool>("user_group_default")
                        .HasColumnName("user_group_default");

                    b.Property<string>("user_group_name")
                        .IsRequired()
                        .HasColumnName("user_group_name")
                        .HasMaxLength(100);

                    b.HasKey("m_user_group_id");

                    b.ToTable("m_user_group");
                });

            modelBuilder.Entity("sahabat_umkm.t_data_anggota", b =>
                {
                    b.Property<int>("t_data_anggota_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("t_data_anggota_id");

                    b.Property<string>("alamat_ktp_anggota")
                        .IsRequired()
                        .HasColumnName("alamat_ktp_anggota");

                    b.Property<string>("alamat_tempat_tinggal_anggota")
                        .IsRequired()
                        .HasColumnName("alamat_tempat_tinggal_anggota");

                    b.Property<string>("asosiasi_komunitas_anggota")
                        .IsRequired()
                        .HasColumnName("asosiasi_komunitas_anggota");

                    b.Property<string>("email_anggota")
                        .IsRequired()
                        .HasColumnName("email_anggota");

                    b.Property<int>("m_jenjang_pendidikan_id")
                        .HasColumnName("m_jenjang_pendidikan_id");

                    b.Property<int>("m_kelurahan_desa_id_ktp_anggota")
                        .HasColumnName("m_kelurahan_desa_id_ktp_anggota");

                    b.Property<int>("m_kelurahan_desa_id_tt_anggota")
                        .HasColumnName("m_kelurahan_desa_id_tt_anggota");

                    b.Property<string>("nama_belakang_anggota")
                        .IsRequired()
                        .HasColumnName("nama_belakang_anggota");

                    b.Property<string>("nama_depan_anggota")
                        .IsRequired()
                        .HasColumnName("nama_depan_anggota");

                    b.Property<string>("nomor_ktp_anggota")
                        .IsRequired()
                        .HasColumnName("nomor_ktp_anggota");

                    b.Property<string>("rt_ktp_anggota")
                        .IsRequired()
                        .HasColumnName("rt_ktp_anggota");

                    b.Property<string>("rt_tempat_tinggal_anggota")
                        .IsRequired()
                        .HasColumnName("rt_tempat_tinggal_anggota");

                    b.Property<string>("rw_ktp_anggota")
                        .IsRequired()
                        .HasColumnName("rw_ktp_anggota");

                    b.Property<string>("rw_tempat_tinggal_anggota")
                        .IsRequired()
                        .HasColumnName("rw_tempat_tinggal_anggota");

                    b.Property<string>("telepon_anggota")
                        .IsRequired()
                        .HasColumnName("telepon_anggota");

                    b.HasKey("t_data_anggota_id");

                    b.HasIndex("m_jenjang_pendidikan_id");

                    b.HasIndex("m_kelurahan_desa_id_ktp_anggota");

                    b.HasIndex("m_kelurahan_desa_id_tt_anggota");

                    b.ToTable("t_data_anggota");
                });

            modelBuilder.Entity("sahabat_umkm.t_data_usaha", b =>
                {
                    b.Property<int>("t_data_usaha_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("t_data_usaha_id");

                    b.Property<string>("alamat_usaha")
                        .IsRequired()
                        .HasColumnName("alamat_usaha");

                    b.Property<string>("deskripsi_usaha")
                        .IsRequired()
                        .HasColumnName("deskripsi_usaha");

                    b.Property<string>("jabatan_bisnis")
                        .IsRequired()
                        .HasColumnName("jabatan_bisnis");

                    b.Property<string>("ktp_usaha")
                        .IsRequired()
                        .HasColumnName("ktp_usaha");

                    b.Property<int>("m_jenis_bidang_usaha_id")
                        .HasColumnName("m_jenis_bidang_usaha_id");

                    b.Property<int>("m_kelurahan_desa_id")
                        .HasColumnName("m_kelurahan_desa_id");

                    b.Property<int>("m_pilihan_omzet_id")
                        .HasColumnName("m_pilihan_omzet_id");

                    b.Property<string>("nama_badan_usaha")
                        .IsRequired()
                        .HasColumnName("nama_badan_usaha");

                    b.Property<string>("nama_bisnis")
                        .IsRequired()
                        .HasColumnName("nama_bisnis");

                    b.Property<string>("npwp_usaha")
                        .IsRequired()
                        .HasColumnName("npwp_usaha");

                    b.Property<string>("sosmed_usaha_fb")
                        .IsRequired()
                        .HasColumnName("sosmed_usaha_fb");

                    b.Property<string>("sosmed_usaha_ig")
                        .IsRequired()
                        .HasColumnName("sosmed_usaha_ig");

                    b.Property<string>("sosmed_usaha_tw")
                        .IsRequired()
                        .HasColumnName("sosmed_usaha_tw");

                    b.Property<int>("t_data_anggota_id")
                        .HasColumnName("t_data_anggota_id");

                    b.Property<string>("tahun_pendirian_usaha")
                        .IsRequired()
                        .HasColumnName("tahun_pendirian_usaha");

                    b.Property<string>("website_usaha")
                        .IsRequired()
                        .HasColumnName("website_usaha");

                    b.HasKey("t_data_usaha_id");

                    b.HasIndex("m_jenis_bidang_usaha_id");

                    b.HasIndex("m_kelurahan_desa_id");

                    b.HasIndex("m_pilihan_omzet_id");

                    b.HasIndex("t_data_anggota_id");

                    b.ToTable("t_data_usaha");
                });

            modelBuilder.Entity("sahabat_umkm.t_kategori_posting", b =>
                {
                    b.Property<int>("t_kategori_posting_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("t_kategori_posting_id");

                    b.Property<string>("nama_kategori_posting")
                        .IsRequired()
                        .HasColumnName("nama_kategori_posting");

                    b.HasKey("t_kategori_posting_id");

                    b.ToTable("t_kategori_posting");
                });

            modelBuilder.Entity("sahabat_umkm.t_posting", b =>
                {
                    b.Property<int>("t_posting_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("t_posting_id");

                    b.Property<string>("isi_posting")
                        .IsRequired()
                        .HasColumnName("isi_posting");

                    b.Property<string>("judul_posting")
                        .IsRequired()
                        .HasColumnName("judul_posting");

                    b.Property<string>("status_posting")
                        .IsRequired()
                        .HasColumnName("status_posting");

                    b.Property<int>("t_kategori_posting_id")
                        .HasColumnName("t_kategori_posting_id");

                    b.Property<DateTime>("tanggal_posting")
                        .HasColumnName("tanggal_posting");

                    b.Property<string>("thumbnail_posting")
                        .IsRequired()
                        .HasColumnName("thumbnail_posting");

                    b.HasKey("t_posting_id");

                    b.HasIndex("t_kategori_posting_id");

                    b.ToTable("t_posting");
                });

            modelBuilder.Entity("sahabat_umkm.feature_map", b =>
                {
                    b.HasOne("sahabat_umkm.m_feature", "m_feature")
                        .WithMany("feature_map")
                        .HasForeignKey("m_feature_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("sahabat_umkm.m_user_group", "m_user_group")
                        .WithMany("feature_map")
                        .HasForeignKey("m_user_group_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("sahabat_umkm.m_feature", b =>
                {
                    b.HasOne("sahabat_umkm.m_feature_group", "m_feature_group")
                        .WithMany("m_feature")
                        .HasForeignKey("m_feature_group_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("sahabat_umkm.m_user", b =>
                {
                    b.HasOne("sahabat_umkm.m_user_group", "m_user_group")
                        .WithMany("m_user")
                        .HasForeignKey("m_user_group_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("sahabat_umkm.t_data_anggota", b =>
                {
                    b.HasOne("sahabat_umkm.m_jenjang_pendidikan", "m_jenjang_pendidikan")
                        .WithMany("t_data_anggota")
                        .HasForeignKey("m_jenjang_pendidikan_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("sahabat_umkm.m_kelurahan_desa", "m_kelurahan_desa_ktp_anggota")
                        .WithMany("t_data_anggota_ktp_anggota")
                        .HasForeignKey("m_kelurahan_desa_id_ktp_anggota")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("sahabat_umkm.m_kelurahan_desa", "m_kelurahan_desa_tt_anggota")
                        .WithMany("t_data_anggota_tt_anggota")
                        .HasForeignKey("m_kelurahan_desa_id_tt_anggota")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("sahabat_umkm.t_data_usaha", b =>
                {
                    b.HasOne("sahabat_umkm.m_jenis_bidang_usaha", "m_jenis_bidang_usaha")
                        .WithMany("t_data_usaha")
                        .HasForeignKey("m_jenis_bidang_usaha_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("sahabat_umkm.m_kelurahan_desa", "m_kelurahan_desa")
                        .WithMany("t_data_usaha")
                        .HasForeignKey("m_kelurahan_desa_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("sahabat_umkm.m_pilihan_omzet", "m_pilihan_omzet")
                        .WithMany("t_data_usaha")
                        .HasForeignKey("m_pilihan_omzet_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("sahabat_umkm.t_data_anggota", "t_data_anggota")
                        .WithMany("t_data_usaha")
                        .HasForeignKey("t_data_anggota_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("sahabat_umkm.t_posting", b =>
                {
                    b.HasOne("sahabat_umkm.t_kategori_posting", "t_kategori_posting")
                        .WithMany("t_posting")
                        .HasForeignKey("t_kategori_posting_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
