//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 20-Oct-17 13:54:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace m_news_context
{
    public partial class m_jenjang_pendidikan {

        public m_jenjang_pendidikan()
        {
            this.t_data_anggota = new List<t_data_anggota>();
            OnCreated();
        }

        public virtual int m_jenjang_pendidikan_id
        {
            get;
            set;
        }

        public virtual string nama_jenjang_pendidikan
        {
            get;
            set;
        }

        public virtual bool status_aktif
        {
            get;
            set;
        }

        public virtual IList<t_data_anggota> t_data_anggota
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
