//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 20-Oct-17 13:52:13
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace m_news_context
{
    public partial class t_data_anggota {

        public t_data_anggota()
        {
            OnCreated();
        }

        public virtual int t_data_anggota_id
        {
            get;
            set;
        }

        public virtual string nama_depan_anggota
        {
            get;
            set;
        }

        public virtual string nama_belakang_anggota
        {
            get;
            set;
        }

        public virtual string email_anggota
        {
            get;
            set;
        }

        public virtual string telepon_anggota
        {
            get;
            set;
        }

        public virtual string nomor_ktp_anggota
        {
            get;
            set;
        }

        public virtual string alamat_ktp_anggota
        {
            get;
            set;
        }

        public virtual string rt_ktp_anggota
        {
            get;
            set;
        }

        public virtual string rw_ktp_anggota
        {
            get;
            set;
        }

        public virtual string alamat_tempat_tinggal_anggota
        {
            get;
            set;
        }

        public virtual string rt_tempat_tinggal_anggota
        {
            get;
            set;
        }

        public virtual string rw_tempat_tinggal_anggota
        {
            get;
            set;
        }

        public virtual string asosiasi_komunitas_anggota
        {
            get;
            set;
        }

        public virtual int m_kelurahan_desa_id_ktp_anggota
        {
            get;
            set;
        }

        public virtual int m_kelurahan_desa_id_tt_anggota
        {
            get;
            set;
        }

        public virtual int m_jenjang_pendidikan_id
        {
            get;
            set;
        }

        public virtual m_kelurahan_desa m_kelurahan_desa_ktp_anggota
        {
            get;
            set;
        }

        public virtual m_kelurahan_desa m_kelurahan_desa_tt_anggota
        {
            get;
            set;
        }

        public virtual m_jenjang_pendidikan m_jenjang_pendidikan
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
