//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 23-Oct-17 11:52:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace sahabat_umkm
{
    [DataContract(IsReference = true)]
    public partial class t_data_usaha {

        public t_data_usaha()
        {
            OnCreated();
        }

        [DataMember(Order=1)]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int t_data_usaha_id
        {
            get;
            set;
        }

        [DataMember(Order=2)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string nama_badan_usaha
        {
            get;
            set;
        }

        [DataMember(Order=3)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string nama_bisnis
        {
            get;
            set;
        }

        [DataMember(Order=4)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string jabatan_bisnis
        {
            get;
            set;
        }

        [DataMember(Order=5)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string deskripsi_usaha
        {
            get;
            set;
        }

        [DataMember(Order=6)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string tahun_pendirian_usaha
        {
            get;
            set;
        }

        [DataMember(Order=7)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string alamat_usaha
        {
            get;
            set;
        }

        [DataMember(Order=8)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int m_jenis_bidang_usaha_id
        {
            get;
            set;
        }

        [DataMember(Order=9)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int m_pilihan_omzet_id
        {
            get;
            set;
        }

        [DataMember(Order=10)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int m_kelurahan_desa_id
        {
            get;
            set;
        }

        [DataMember(Order=11)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string website_usaha
        {
            get;
            set;
        }

        [DataMember(Order=12)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string sosmed_usaha_fb
        {
            get;
            set;
        }

        [DataMember(Order=13)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string sosmed_usaha_ig
        {
            get;
            set;
        }

        [DataMember(Order=14)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string sosmed_usaha_tw
        {
            get;
            set;
        }

        [DataMember(Order=15)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string ktp_usaha
        {
            get;
            set;
        }

        [DataMember(Order=16)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string npwp_usaha
        {
            get;
            set;
        }

        [DataMember(Order=17)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int t_data_anggota_id
        {
            get;
            set;
        }

        public virtual m_jenis_bidang_usaha m_jenis_bidang_usaha
        {
            get;
            set;
        }

        public virtual m_pilihan_omzet m_pilihan_omzet
        {
            get;
            set;
        }

        public virtual m_kelurahan_desa m_kelurahan_desa
        {
            get;
            set;
        }

        public virtual t_data_anggota t_data_anggota
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
