//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 23-Oct-17 11:03:20
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace m_news_context
{
    public partial class m_feature {

        public m_feature()
        {
            this.feature_map = new List<feature_map>();
            OnCreated();
        }

        public virtual int m_feature_id
        {
            get;
            set;
        }

        public virtual string feature_name
        {
            get;
            set;
        }

        public virtual int feature_sequence
        {
            get;
            set;
        }

        public virtual string feature_url
        {
            get;
            set;
        }

        public virtual string feature_icon
        {
            get;
            set;
        }

        public virtual bool feature_private
        {
            get;
            set;
        }

        public virtual int m_feature_group_id
        {
            get;
            set;
        }

        public virtual IList<feature_map> feature_map
        {
            get;
            set;
        }

        public virtual m_feature_group m_feature_group
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
