//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 25-Oct-17 11:36:25
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace sahabat_umkm
{
    [DataContract(IsReference = true)]
    public partial class t_data_anggota {

        public t_data_anggota()
        {
            this.t_data_usaha = new List<t_data_usaha>();
            this.t_info_bekraf = new List<t_info_bekraf>();
            OnCreated();
        }

        [DataMember(Order=1)]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int t_data_anggota_id
        {
            get;
            set;
        }

        [DataMember(Order=2)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string nama_depan_anggota
        {
            get;
            set;
        }

        [DataMember(Order=3)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string nama_belakang_anggota
        {
            get;
            set;
        }

        [DataMember(Order=4)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string email_anggota
        {
            get;
            set;
        }

        [DataMember(Order=5)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string telepon_anggota
        {
            get;
            set;
        }

        [DataMember(Order=6)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string nomor_ktp_anggota
        {
            get;
            set;
        }

        [DataMember(Order=7)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string alamat_ktp_anggota
        {
            get;
            set;
        }

        [DataMember(Order=8)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string rt_ktp_anggota
        {
            get;
            set;
        }

        [DataMember(Order=9)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string rw_ktp_anggota
        {
            get;
            set;
        }

        [DataMember(Order=10)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string alamat_tempat_tinggal_anggota
        {
            get;
            set;
        }

        [DataMember(Order=11)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string rt_tempat_tinggal_anggota
        {
            get;
            set;
        }

        [DataMember(Order=12)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string rw_tempat_tinggal_anggota
        {
            get;
            set;
        }

        [DataMember(Order=13)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string asosiasi_komunitas_anggota
        {
            get;
            set;
        }

        [DataMember(Order=14)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int m_kelurahan_desa_id_ktp_anggota
        {
            get;
            set;
        }

        [DataMember(Order=15)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int m_kelurahan_desa_id_tt_anggota
        {
            get;
            set;
        }

        [DataMember(Order=16)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int m_jenjang_pendidikan_id
        {
            get;
            set;
        }

        [DataMember(Order=17)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual bool kesediaan_mendaftar_sebagai_anggota
        {
            get;
            set;
        }

        [DataMember(Order=18)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual System.DateTime tanggal_pendaftaran_anggota
        {
            get;
            set;
        }

        public virtual m_kelurahan_desa m_kelurahan_desa_ktp_anggota
        {
            get;
            set;
        }

        public virtual m_kelurahan_desa m_kelurahan_desa_tt_anggota
        {
            get;
            set;
        }

        public virtual m_jenjang_pendidikan m_jenjang_pendidikan
        {
            get;
            set;
        }

        [DataMember(Order=19, EmitDefaultValue=false)]
        public virtual IList<t_data_usaha> t_data_usaha
        {
            get;
            set;
        }

        [DataMember(Order=20, EmitDefaultValue=false)]
        public virtual IList<t_info_bekraf> t_info_bekraf
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
