//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 20-Oct-17 13:52:13
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace m_news_context
{
    public partial class m_user {

        public m_user()
        {
            OnCreated();
        }

        public virtual int m_user_id
        {
            get;
            set;
        }

        public virtual string user_name
        {
            get;
            set;
        }

        public virtual string user_password
        {
            get;
            set;
        }

        public virtual string user_email
        {
            get;
            set;
        }

        public virtual bool user_active
        {
            get;
            set;
        }

        public virtual int m_user_group_id
        {
            get;
            set;
        }

        public virtual m_user_group m_user_group
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
